import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import RootProviders from "@/providers/root-providers/root-providers";
import QueryProvider from "@/providers/query-provider/query-provider";

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className="dark"
            style={{
            colorScheme: "dark",
        }}
    >
        <body className={inter.className}>
            <QueryProvider>
                <RootProviders>
                        {children}
                </RootProviders>
            </QueryProvider>
        </body>
    </html>
    );
}
